name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get install valac libgee-0.8-dev libgtk-3-dev libcairo-dev libjson-glib-dev libsoup2.4-dev libvte-2.91-dev xvfb
          pip install meson
          pip install ninja
      - name: Build
        run: |
          meson build -Ddebug=true -Db_coverage=true
          ninja -C build
      - name: Run tests
        run: |
          xvfb-run --auto-servernum --server-num=1 /home/runner/work/dockery/dockery/build/tests/dockery-test
          xvfb-run --auto-servernum --server-num=1 /home/runner/work/dockery/dockery/build/subprojects/livechart/tests/livechart-test
          xvfb-run --auto-servernum --server-num=1 /home/runner/work/dockery/dockery/build/subprojects/vala-docker/tests/vala-docker-test
      - name: Send coverage report
        run: bash <(curl -s https://codecov.io/bash)        